# Generated by Django 5.0 on 2023-12-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_count_options_alter_edges_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='count',
            field=models.IntegerField(verbose_name='Количество'),
        ),
    ]
