# Generated by Django 5.0 on 2023-12-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_count_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='names',
            name='id',
        ),
        migrations.AlterField(
            model_name='names',
            name='num',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер'),
        ),
    ]
